apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: amq-streams-example-kafka

resources:
  - amq-streams-example-kafka.yaml
  - amq-streams-example-service-registry.yaml
  - topics